name: flutter_chat_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.1
  bloc: ^8.1.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.0.0+1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  path_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
